[package]
name = "rustcompiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = {version = "0.1.12"}
prev-iter = { version = "0.1.2" }